stages:
  - test
  - deploy

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - python -m unittest discover -s hello_devops

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."

